# Generated by Django 5.1.4 on 2026-05-06 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0001_initial'),
        ('qualifications', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.learnerprofile'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_enrollments', to='qualifications.qualification'),
        ),
        migrations.AddField(
            model_name='reasonableadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reasonableadjustment',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasonable_adjustments', to='users.learnerprofile'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['learner', 'status'], name='enrollments_learner_61b5e4_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['qualification', 'status'], name='enrollments_qualifi_71bfc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('learner', 'qualification', 'cohort'), name='unique_learner_enrollment_cohort'),
        ),
        migrations.AddIndex(
            model_name='reasonableadjustment',
            index=models.Index(fields=['learner', 'accepted'], name='reasonable__learner_5ed66d_idx'),
        ),
        migrations.AddConstraint(
            model_name='reasonableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('accepted', False), ('denied', False), _connector='OR'), name='reasonable_adjustment_not_accepted_and_denied'),
        ),
        migrations.AddConstraint(
            model_name='reasonableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('denied', False), models.Q(('denial_reason', ''), _negated=True), _connector='OR'), name='reasonable_adjustment_denial_has_reason'),
        ),
        migrations.AddConstraint(
            model_name='reasonableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('extra_time_minutes__lte', 240)), name='reasonable_adjustment_extra_time_lte_240'),
        ),
    ]
