# Generated by Django 5.1.4 on 2026-05-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_learner_61b5e4_idx',
            old_name='enrollment_learner_status_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_qualifi_71bfc5_idx',
            old_name='enrollment_qualification_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reasonableadjustment',
            new_name='reasonable__learner_5ed66d_idx',
            old_name='reasonable_learner_accepted_idx',
        ),
    ]
