# Generated by Django 5.2.14 on 2026-05-15 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_initial'),
        ('users', '0002_alter_learnerprofile_uln'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reasonableadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('accepted', True), ('denied', True), _connector='OR'), name='reasonable_adjustment_must_be_accepted_or_denied'),
        ),
    ]
