# Generated by Django 5.1.4 on 2026-05-09 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single answer'), ('multiple', 'Multiple answer')], default='single', max_length=10)),
                ('options', models.JSONField(default=list)),
                ('correct_answers', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
