# Generated by Django 5.1.4 on 2026-05-06 18:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualifications', '0002_constraints_and_slug_safety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Single answer'), ('multiple', 'Multiple answer')], default='single', max_length=10)),
                ('options', models.JSONField(default=list)),
                ('correct_answers', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='qualifications.qualification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['qualification', 'is_active'], name='questions_q_qualifi_69d386_idx')],
            },
        ),
    ]
