# Generated by Django 5.1.4 on 2026-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image_url',
        ),
        migrations.AddField(
            model_name='question',
            name='image_qs',
            field=models.ImageField(blank=True, null=True, upload_to='questions/images/'),
        ),
    ]
