# Generated by Django 5.1.4 on 2026-05-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_question_image_url_question_image_qs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image_qs',
            field=models.ImageField(blank=True, null=True, upload_to='questions_images/'),
        ),
    ]
