# Generated by Django 5.1.4 on 2026-05-13 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='uln',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'ULN must be exactly 10 digits.')]),
        ),
    ]
