# Generated by Django 5.1.4 on 2026-05-01 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnerprofile',
            name='uln',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'ULN must be exactly 10 digits.')]),
        ),
    ]
