# Generated by Django 5.1.4 on 2026-05-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_learner_uln_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnerprofile',
            name='postcode',
        ),
    ]
