# Generated by Django 5.1.4 on 2026-05-06 19:11

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('level-1', 'Level 1'), ('level-2', 'Level 2'), ('level-3', 'Level 3'), ('level-4', 'Level 4'), ('level-5', 'Level 5'), ('level-6', 'Level 6'), ('level-7', 'Level 7')], max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QualificationEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort', models.CharField(db_index=True, max_length=40)),
                ('employer', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=16)),
                ('enrolled_at', models.DateField(db_index=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('withdrawn_at', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='QualificationUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['qualification', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('default_questions_per_exam', models.PositiveIntegerField(default=40)),
                ('default_time_limit_minutes', models.PositiveIntegerField(default=60)),
                ('default_pass_boundary', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_merit_boundary', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_distinction_boundary', models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_bank_size', models.PositiveIntegerField(default=100)),
                ('recommended_bank_size', models.PositiveIntegerField(default=200)),
                ('resit_unseen_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('resit_fail_margin_percent', models.PositiveSmallIntegerField(default=5)),
                ('max_resit_attempts', models.PositiveSmallIntegerField(default=2)),
                ('resit_cooldown_days', models.PositiveSmallIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='qualifications.level')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
