# Generated by Django 5.2.14 on 2026-05-06 11:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('numeric_value', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['numeric_value'],
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='qualificati_is_acti_d746b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('default_questions_per_exam', models.PositiveIntegerField(default=40)),
                ('default_time_limit_minutes', models.PositiveIntegerField(default=60)),
                ('default_pass_boundary', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_merit_boundary', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_distinction_boundary', models.PositiveSmallIntegerField(default=85, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('min_bank_size', models.PositiveIntegerField(default=100)),
                ('recommended_bank_size', models.PositiveIntegerField(default=200)),
                ('resit_unseen_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('resit_fail_margin_percent', models.PositiveSmallIntegerField(default=5)),
                ('max_resit_attempts', models.PositiveSmallIntegerField(default=2)),
                ('resit_cooldown_days', models.PositiveSmallIntegerField(default=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='qualifications.level')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='qualifications.sector')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QualificationEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort', models.CharField(db_index=True, max_length=40)),
                ('employer', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn'), ('completed', 'Completed'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=16)),
                ('enrolled_at', models.DateField(db_index=True)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('withdrawn_at', models.DateField(blank=True, null=True)),
                ('withdrawal_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(limit_choices_to={'role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='qualifications.qualification')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['learner', 'status'], name='qualificati_learner_e6a4cf_idx'), models.Index(fields=['qualification', 'status'], name='qualificati_qualifi_a9476b_idx'), models.Index(fields=['status', '-enrolled_at'], name='qualificati_status_50bdf6_idx')],
                'unique_together': {('learner', 'qualification', 'cohort')},
            },
        ),
        migrations.CreateModel(
            name='QualificationUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='qualifications.qualification')),
            ],
            options={
                'ordering': ['qualification', 'sort_order'],
                'indexes': [models.Index(fields=['qualification', 'sort_order'], name='qualificati_qualifi_48fb8c_idx')],
                'unique_together': {('qualification', 'code')},
            },
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['is_active', 'title'], name='qualificati_is_acti_fce0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['sector', 'level', 'is_active'], name='qualificati_sector__6a0a25_idx'),
        ),
    ]
