# Generated by Django 5.1.4 on 2026-05-09 18:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationenrollment',
            name='learner',
            field=models.ForeignKey(limit_choices_to={'role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qualificationenrollment',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='qualifications.qualification'),
        ),
        migrations.AddField(
            model_name='qualificationunit',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='qualifications.qualification'),
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['is_active', 'sort_order'], name='qualificati_is_acti_d746b0_idx'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='qualifications.sector'),
        ),
        migrations.AddIndex(
            model_name='qualificationenrollment',
            index=models.Index(fields=['learner', 'status'], name='qualificati_learner_e6a4cf_idx'),
        ),
        migrations.AddIndex(
            model_name='qualificationenrollment',
            index=models.Index(fields=['qualification', 'status'], name='qualificati_qualifi_a9476b_idx'),
        ),
        migrations.AddIndex(
            model_name='qualificationenrollment',
            index=models.Index(fields=['status', '-enrolled_at'], name='qualificati_status_50bdf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualificationenrollment',
            constraint=models.UniqueConstraint(fields=('learner', 'qualification', 'cohort'), name='unique_qualification_enrollment_cohort'),
        ),
        migrations.AddIndex(
            model_name='qualificationunit',
            index=models.Index(fields=['qualification', 'sort_order'], name='qualificati_qualifi_48fb8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualificationunit',
            constraint=models.UniqueConstraint(fields=('qualification', 'code'), name='unique_qualification_unit_code'),
        ),
        migrations.AddConstraint(
            model_name='qualificationunit',
            constraint=models.CheckConstraint(condition=models.Q(('weight__gt', 0)), name='qualification_unit_weight_positive'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['is_active', 'title'], name='qualificati_is_acti_fce0f8_idx'),
        ),
        migrations.AddIndex(
            model_name='qualification',
            index=models.Index(fields=['sector', 'level', 'is_active'], name='qualificati_sector__6a0a25_idx'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('default_pass_boundary__gte', 0), ('default_pass_boundary__lte', 100), ('default_merit_boundary__gte', 0), ('default_merit_boundary__lte', 100), ('default_distinction_boundary__gte', 0), ('default_distinction_boundary__lte', 100)), name='qualification_default_boundaries_0_to_100'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('default_pass_boundary__lt', models.F('default_merit_boundary')), ('default_merit_boundary__lt', models.F('default_distinction_boundary'))), name='qualification_default_boundaries_ordered'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('min_bank_size__lte', models.F('recommended_bank_size'))), name='qualification_bank_size_ordered'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('resit_unseen_ratio__gte', Decimal('0.00')), ('resit_unseen_ratio__lte', Decimal('1.00'))), name='qualification_resit_unseen_ratio_0_to_1'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('resit_fail_margin_percent__gte', 0), ('resit_fail_margin_percent__lte', 100)), name='qualification_resit_fail_margin_0_to_100'),
        ),
        migrations.AddConstraint(
            model_name='qualification',
            constraint=models.CheckConstraint(condition=models.Q(('default_questions_per_exam__gt', 0), ('default_time_limit_minutes__gt', 0)), name='qualification_exam_defaults_positive'),
        ),
    ]
