# Generated by Django 5.1.4 on 2026-05-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
