# Generated by Django 5.1.4 on 2026-05-06 18:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'invigilator'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Invigilator availability',
                'ordering': ['user', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCentre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text='Short uppercase code shown on the invigilator profile.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]{3,20}$', 'Provider code must be uppercase letters/digits, e.g. PRV001')])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('postcode', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(blank=True, default='United Kingdom', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider centre',
                'verbose_name_plural': 'Provider centres',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='invigilator_code_3b3ba0_idx'), models.Index(fields=['is_active'], name='invigilator_is_acti_adc884_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvigilatorProviderLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=True, help_text="The invigilator's main centre. Used when only one code is shown in UI.")),
                ('started_at', models.DateField(default=django.utils.timezone.now)),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'invigilator'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_links', to='invigilators.providercentre')),
            ],
            options={
                'ordering': ['-is_primary', 'provider__name'],
                'unique_together': {('user', 'provider')},
            },
        ),
    ]
