# Generated by Django 5.1.4 on 2026-05-06 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invigilators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invigilatoravailability',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'invigilator'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invigilatorproviderlink',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'invigilator'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='providercentre',
            index=models.Index(fields=['code'], name='invigilator_code_3b3ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='providercentre',
            index=models.Index(fields=['is_active'], name='invigilator_is_acti_adc884_idx'),
        ),
        migrations.AddField(
            model_name='invigilatorproviderlink',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_links', to='invigilators.providercentre'),
        ),
        migrations.AlterUniqueTogether(
            name='invigilatorproviderlink',
            unique_together={('user', 'provider')},
        ),
    ]
