# Generated by Django 5.1.4 on 2026-05-09 18:58

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('version_number', models.CharField(default='v1.0', max_length=10)),
                ('exam_type', models.CharField(choices=[('live', 'Live'), ('mock', 'Mock')], default='live', max_length=10)),
                ('questions_per_exam', models.PositiveIntegerField()),
                ('time_limit_minutes', models.PositiveIntegerField()),
                ('shuffle_questions', models.BooleanField(default=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('strict_mode', models.BooleanField(default=True)),
                ('grade_distinction', models.PositiveSmallIntegerField(default=85)),
                ('grade_merit', models.PositiveSmallIntegerField(default=70)),
                ('grade_pass', models.PositiveSmallIntegerField(default=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_percent', models.PositiveSmallIntegerField()),
                ('correct_count', models.PositiveIntegerField()),
                ('total_questions', models.PositiveIntegerField()),
                ('grade', models.CharField(choices=[('distinction', 'Distinction'), ('merit', 'Merit'), ('pass', 'Pass'), ('did_not_pass', 'Did Not Pass')], max_length=20)),
                ('passed', models.BooleanField()),
                ('time_taken_seconds', models.PositiveIntegerField()),
                ('violation_count', models.PositiveIntegerField(default=0)),
                ('question_ids', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('invigilator_name', models.CharField(blank=True, default='', max_length=255)),
                ('reasonable_adjustments', models.TextField(blank=True, default='')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('exam_date', models.DateField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField()),
                ('pin_window_start', models.DateTimeField(blank=True, null=True)),
                ('pin_window_end', models.DateTimeField(blank=True, null=True)),
                ('allow_immediate_start', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=6)),
                ('pin_active', models.BooleanField(default=True)),
                ('question_set', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=15)),
                ('id_verified', models.BooleanField(default=False)),
                ('completed_successfully', models.BooleanField(blank=True, null=True)),
                ('incident_notes', models.TextField(blank=True, default='')),
                ('reasonable_adjustments', models.TextField(blank=True, default='')),
                ('extra_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('draft_answers', models.JSONField(blank=True, default=list)),
                ('draft_current_question_index', models.PositiveIntegerField(default=0)),
                ('draft_flagged_question_indexes', models.JSONField(blank=True, default=list)),
                ('draft_remaining_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('draft_updated_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='IntegrityViolation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('fullscreen_exit', 'Fullscreen Exit'), ('right_click', 'Right Click'), ('copy_paste', 'Copy/Paste'), ('devtools', 'DevTools'), ('print_attempt', 'Print Attempt'), ('time_exceeded', 'Time Exceeded')], max_length=30)),
                ('detail', models.CharField(max_length=255)),
                ('question_number', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerSeenQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RetakeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('denial_reason', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
