# Generated by Django 5.1.4 on 2026-05-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examconfig',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_configs', to='qualifications.qualification'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.examconfig'),
        ),
    ]
