# Generated by Django 5.1.4 on 2026-05-06 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerseenquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_records', to='questions.question'),
        ),
        migrations.AddField(
            model_name='learnerseenquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_question_records', to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='retakerequest',
            name='exam_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.examconfig'),
        ),
        migrations.AddField(
            model_name='retakerequest',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retake_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='retakerequest',
            name='new_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_retake_request', to='exams.examsession'),
        ),
        migrations.AddField(
            model_name='retakerequest',
            name='previous_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retake_requests', to='exams.examresult'),
        ),
        migrations.AddField(
            model_name='retakerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_retakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['learner', 'status'], name='exams_exams_learner_20b1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['invigilator', 'scheduled_date'], name='exams_exams_invigil_81199f_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['learner', 'exam_config'], name='exams_examr_learner_c2993e_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['qualification', 'submitted_at'], name='exams_examr_qualifi_830596_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerseenquestion',
            index=models.Index(fields=['learner', 'qualification'], name='exams_learn_learner_65f0c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerseenquestion',
            constraint=models.UniqueConstraint(fields=('learner', 'question'), name='unique_seen_question_per_learner'),
        ),
        migrations.AddConstraint(
            model_name='retakerequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('previous_result',), name='unique_pending_retake_per_result'),
        ),
    ]
