# Generated by Django 5.2.14 on 2026-05-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examsession_enrollment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examsession',
            new_name='exams_exams_enrollm_80020e_idx',
            old_name='exams_exams_enrollm_9b60ad_idx',
        ),
    ]
