# Generated by Django 5.2.14 on 2026-05-24 09:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_rename_exams_exams_enrollm_9b60ad_idx_exams_exams_enrollm_80020e_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examconfig',
            name='scenario_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='examsession',
            name='scenario_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LearnerSeenScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(limit_choices_to={'role': 'learner'}, on_delete=django.db.models.deletion.CASCADE, related_name='seen_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
