# Generated by Django 5.2.14 on 2026-05-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_examconfig_scenario_rules_and_more'),
        ('questions', '0005_question_scenario_order_scenario_question_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnerseenscenario',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_records', to='questions.scenario'),
        ),
        migrations.AddField(
            model_name='learnerseenscenario',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seen_scenario_records', to='exams.examsession'),
        ),
        migrations.AddIndex(
            model_name='learnerseenscenario',
            index=models.Index(fields=['learner'], name='exams_learn_learner_0b26b9_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerseenscenario',
            constraint=models.UniqueConstraint(fields=('learner', 'scenario'), name='unique_seen_scenario_per_learner'),
        ),
    ]
