# Generated by Django 5.2.14 on 2026-05-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_learnerseenscenario_scenario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examconfig',
            name='cert_validity_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Certificate validity in months. 0 = no expiry. Null = not set.', null=True),
        ),
    ]
