name: Leadedge PROD CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy PROD
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://examapi.leadedgeltd.org

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify SSH key
        run: |
          if [ -z "${{ secrets.LEADEDGE_SSH_PRIVATE_KEY }}" ]; then
            echo "SSH key missing"
            exit 1
          else
            echo "SSH key detected"
          fi

      - name: Upload code to PROD server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LEADEDGE_SSH_HOST }}
          username: ${{ secrets.LEADEDGE_SSH_USER }}
          key: ${{ secrets.LEADEDGE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.LEADEDGE_SSH_PORT }}
          source: "./"
          target: "/var/www/leadedge/backend/production"
          strip_components: 1
          rm: false
          exclude: ".env,.env.prod,.env.dev,.env.example,tests/,pytest.ini,examinationleadedge/settings/test.py"

      - name: Deploy containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.LEADEDGE_SSH_HOST }}
          username: ${{ secrets.LEADEDGE_SSH_USER }}
          key: ${{ secrets.LEADEDGE_SSH_PRIVATE_KEY }}
          port: ${{ secrets.LEADEDGE_SSH_PORT }}
          script: |
            cd /var/www/leadedge/backend/production
            make rebuild
            sudo systemctl reload nginx
            echo "PROD deployment completed"
